-- ========================================================
-- SUPABASE POSTGRESQL SCHEMA & POLICIES FOR RECTRACKER
-- ========================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL DEFAULT 'RECRUITER',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 2. CANDIDATES TABLE
CREATE TABLE IF NOT EXISTS public.candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(30) NOT NULL,
    skills TEXT NOT NULL,
    years_of_experience NUMERIC(4, 1) NOT NULL DEFAULT 0.0,
    current_company VARCHAR(150),
    target_role VARCHAR(150) NOT NULL,
    expected_ctc NUMERIC(12, 2) NOT NULL DEFAULT 0.0,
    resume_path VARCHAR(500),
    status VARCHAR(50) NOT NULL DEFAULT 'APPLIED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 3. INTERVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.interviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    interviewer_name VARCHAR(150) NOT NULL,
    round_type VARCHAR(50) NOT NULL,
    scheduled_at TIMESTAMP WITH TIME ZONE NOT NULL,
    location_or_link VARCHAR(500),
    status VARCHAR(50) NOT NULL DEFAULT 'SCHEDULED',
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 4. FEEDBACKS TABLE
CREATE TABLE IF NOT EXISTS public.feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    interview_id BIGINT NOT NULL REFERENCES public.interviews(id) ON DELETE CASCADE,
    candidate_id BIGINT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    interviewer_name VARCHAR(150) NOT NULL,
    technical_rating INT NOT NULL CHECK (technical_rating BETWEEN 1 AND 5),
    communication_rating INT NOT NULL CHECK (communication_rating BETWEEN 1 AND 5),
    problem_solving_rating INT NOT NULL CHECK (problem_solving_rating BETWEEN 1 AND 5),
    overall_recommendation VARCHAR(50) NOT NULL,
    comments TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- 5. OFFERS TABLE
CREATE TABLE IF NOT EXISTS public.offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id BIGINT NOT NULL REFERENCES public.candidates(id) ON DELETE CASCADE,
    job_title VARCHAR(150) NOT NULL,
    department VARCHAR(150) NOT NULL,
    base_salary NUMERIC(12, 2) NOT NULL,
    joining_date DATE NOT NULL,
    valid_until DATE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW())
);

-- ENABLE ROW LEVEL SECURITY (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.offers ENABLE ROW LEVEL SECURITY;

-- CREATE PERMISSIVE POLICIES FOR ANONYMOUS/AUTHENTICATED ACCESS
CREATE POLICY "Allow public read candidates" ON public.candidates FOR SELECT USING (true);
CREATE POLICY "Allow public insert candidates" ON public.candidates FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update candidates" ON public.candidates FOR UPDATE USING (true);

CREATE POLICY "Allow public read interviews" ON public.interviews FOR SELECT USING (true);
CREATE POLICY "Allow public insert interviews" ON public.interviews FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read feedbacks" ON public.feedbacks FOR SELECT USING (true);
CREATE POLICY "Allow public insert feedbacks" ON public.feedbacks FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public read offers" ON public.offers FOR SELECT USING (true);
CREATE POLICY "Allow public insert offers" ON public.offers FOR INSERT WITH CHECK (true);
